### ISSUE TITLE
install_options not respected

### ISSUE THREAD

**Issue by enthooz** [boxen/puppet-homebrew#12]
Homebrew doesn't seem to be respecting `install_options` passed.  For example, I've tried both:

```
Package <| title == 'boxen/brews/nginx' |> {
  install_options => '--with-passenger'
}
```

And:

```
Package <| title == 'boxen/brews/nginx' |> {
  install_options => ['--with-passenger']
}
```

In both cases, the precompiled binary is installed.  I've made a [modification](https://github.com/enthooz/puppet-homebrew/commit/e7c1a439baab89ce31cf6445a708d3281a644b96) to `puppet-homebrew` to fix this for myself.  I feel like this shouldn't be necessary and that I must be missing something.

**Comment by jacobbednarz** [comment]
This has been sitting for 3 years - would you mind testing this with the latest version and opening a new issue if the issue is still present?
