### ISSUE TITLE
Upgrading from version 1.0.0 seems to break puppet-tmux due to options used to compile boxen's tmux binary

### ISSUE THREAD

**Issue by goxberry** [boxen/puppet-homebrew#17]
A detailed description of the bug in puppet-tmux and attempted fixes is at https://github.com/boxen/puppet-tmux/issues/1. @dieterdemeyer and I agree that based on the current evidence, it looks like the cause of the puppet-tmux bug might be changes in puppet-homebrew.

Installing tmux from source via homebrew seems to fix the issues, so a potential fix would be to add a feature that implements install options (which seems to relate to https://github.com/boxen/puppet-homebrew/issues/12).

**Comment by jacobbednarz** [comment]
`puppet-tmux` has been deprecated in favour of using homebrew/cask directly (https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17).
