### ISSUE TITLE
S3 cached binaries incompatible with all but most recent Macs

### ISSUE THREAD

**Issue by mroth** [boxen/puppet-homebrew#18]
Whatever method is being used to generate the cached boxen version of homebrew binary bottles that are stored on S3 seems to be generating binaries that will die fatally on anything but the newest intel architecture macs.

See, for example,
boxen/puppet-homebrew#17 
boxen/puppet-emacs#5

This affects Macs that are not very old at all, for example, 2011 model Macbook Airs (current revision) that use Core2Duo processors.

I'm not sure if there is a way to generate more compatible binaries?  (If not, machines that cannot use the precompiled binaries should not download them from S3, and instead compile from source. As it is currently, they happily install a bunch of broken binaries, which borks all of boxen (and other things) since that includes a broken version of git.)

**Comment by mikemcquaid** [comment]
This is now fixed, `script/sync` in the main boxen repo will refuse to upload if it hasn't been built as a "real" bottle.
