### ISSUE TITLE
need info on how to install with options

### ISSUE THREAD

**Issue by thepian** [boxen/puppet-homebrew#26]
When you do 
brew install cairo
brew install pycairo

It reports to go well, but 

python -c "import cairo"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cairo

I then uninstalled them and followed this:

http://pydanny.com/installing-pycairo-on-mountain-lion.html

How would that be configured with a boxen project?

It would be great if you can you add a note on how to pass options

**Comment by mikemcquaid** [comment]
Options are documented in the README.
