### ISSUE TITLE
brew install vs brew boxen-install

### ISSUE THREAD

**Issue by nonrational** [boxen/puppet-homebrew#32]
Why are these two commands producing two different download URLs for phantomjs?

naked brew => https://downloads.sf.net/project/machomebrew/Bottles/phantomjs-1.9.2.mavericks.bottle.1.tar.gz
boxen's brew => https://phantomjs.googlecode.com/files/phantomjs-1.9.2-source.zip

The googlecode.com is actually in `/opt/boxen/homebrew/Library/Formula/phantomjs.rb` but both claim to load that formula.
No clue where the naked brew's sourceforge Bottle url is being built.

Would the boxen monkeypatches be overriding some newer URL generation in homebrew somehow?

```
aethon:~$ brew install -dv phantomjs
/opt/boxen/homebrew/Library/brew.rb: loading /opt/boxen/homebrew/Library/Formula/phantomjs.rb
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/phantomjs-1.9.2.mavericks.bottle.1.tar.gz
/usr/bin/curl -f#LA Homebrew 0.9.5 (Ruby 1.8.7-358; Mac OS X 10.9) https://downloads.sf.net/project/machomebrew/Bottles/phantomjs-1.9.2.mavericks.bottle.1.tar.gz -C 0 -o /opt/boxen/cache/homebrew/phantomjs-1.9.2.mavericks.bottle.1.tar.gz.incomplete
^C
aethon:~$ brew boxen-install -dv phantomjs
/opt/boxen/homebrew/Library/brew.rb: loading /opt/boxen/homebrew/Library/Formula/phantomjs.rb
==> Downloading https://phantomjs.googlecode.com/files/phantomjs-1.9.2-source.zip
/usr/bin/curl -f#LA Homebrew 0.9.5 (Ruby 1.8.7-358; Mac OS X 10.9) https://phantomjs.googlecode.com/files/phantomjs-1.9.2-source.zip -C 0 -o /opt/boxen/cache/homebrew/phantomjs-1.9.2.zip.incomplete
```

**Comment by mikemcquaid** [comment]
This should be fixed now that Boxen will use Homebrew's bottles when they are available and Boxen's are not.
