### ISSUE TITLE
php55-sphinx failed to build on 10.9.2

### ISSUE THREAD

**Issue by sheldon** [boxen/puppet-homebrew#40]
Hi

I'm having trouble installing php55-sphinx. Pretty sure it's a pathing issue with homebrew being installed in boxen's /opt/boxen/homebrew instead of /usr/local, but I'm unsure of how to resolve it.

Here's the error:
configure: error: Cannot find libsphinxclient headers

And the gist of my logs: https://gist.github.com/anonymous/9683930

Any help greatly appreciated.

For reference I've already asked the homebrew-php guys for help here https://github.com/josegonzalez/homebrew-php/issues/1049, unfortunately they weren't sure what the problem could be.

**Comment by jacobbednarz** [comment]
Closing due to being over 12 months old. Please let me know if you'd like to continue on this.
