### ISSUE TITLE
brew update if a formula isn't compatible with the version of homebrew

### ISSUE THREAD

**Issue by wfarr** [boxen/puppet-homebrew#41]
tl;dr

``` puppet
Homebrew::Formula <| |>
  -> Homebrew::Tap <| |>
  -> Exec['brew readall && brew tap --repair']
  ~> Exec['brew update']
  -> Package <| |>
```

This should ensure that homebrew is in a state such that we can install packages when it comes time to, even if we're not in a good state at the start of the run.

/cc @dgoodlad

**Comment by mikemcquaid** [comment]
Closing this as it's as fixed as it will be.
