### ISSUE TITLE
config.pp and formula.pp pointing to different taps directory?

### ISSUE THREAD

**Issue by todzheng** [boxen/puppet-homebrew#53]
config.pp (https://github.com/boxen/puppet-homebrew/blob/master/manifests/config.pp) is pointing to  $brewsdir   = "${tapsdir}/boxen-brews"

while formula.pp (https://github.com/boxen/puppet-homebrew/blob/master/manifests/formula.pp), they are pointing to different home-brew taps

**Comment by mikemcquaid** [comment]
This is fixed now.
