### ISSUE TITLE
Question: possible to remove boxen's dependency ?

### ISSUE THREAD

**Issue by ynk** [boxen/puppet-homebrew#59]
Hi,

I'm quite average in puppet, and i was thinking about doing my own puppet script to install/maintain my workstation when i found boxen. I'm quite impressed, but still i don't understand why all your modules are built on top of boxen/boxen. It means to me that it's not usable outside of boxen environment, thus not portable so far. Would it be possible to open it a little more :) ?

Thanks for answering

**Comment by mikemcquaid** [comment]
Closing due to @adamnbowen's comment.
