### ISSUE TITLE
Question: How to use bottles?

### ISSUE THREAD

**Issue by pgib** [boxen/puppet-homebrew#60]
I'd really like to make use of bottles so that each person on my team doesn't have to spend hours compiling the same stuff; however, I'm having a rough time figuring out how to actually do this.

I've set `BOXEN_S3_BUCKET` in my `config/boxen.rb`, and have created a `homebrew/yosemite` path ([which I assume is correct](https://github.com/boxen/puppet-homebrew/blob/153bcc9f7c1245471e45e3a5f6cfa7f8f91fb348/files/boxen-bottle-hooks.rb#L21)) within that bucket. I'm starting with just one formula to test with (mongodb). When I build locally, a bottle is automatically created in `/opt/boxen/cache/homebrew`, though it has a .tar.gz extension instead of the [.tar.bz2](https://github.com/boxen/puppet-homebrew/blob/153bcc9f7c1245471e45e3a5f6cfa7f8f91fb348/files/boxen-bottle-hooks.rb#L12) that the monkey patch seems to want.

I uploaded the generated one _and_ a .tar.bz2 version, but it's still not getting used. I forked the [boxen/puppet-mongodb](https://github.com/boxen/puppet-mongodb) repo to a) use a different version of MongoDB, and b) to specify the `bottle` block (which I can only assume is needed?)...

```ruby
bottle do
  cellar :any
  sha1 "44779e646de756c1a1b5d349f55e978d0681f5bf" => :yosemite
end
```

At this point, I'm out of ideas. Any pointers or advice would be greatly appreciated. I'm happy to write up some documentation for everyone else once things are clear.

Thanks!

Until then...

![confused](https://dl.dropboxusercontent.com/u/31250/gifs/confused-indianajones.gif)

**Comment by mikemcquaid** [comment]
Hopefully your questions were answered here.
