### ISSUE TITLE
Is setting LDFLAG and CFLAG the right choice?

### ISSUE THREAD

**Issue by lethjakman** [boxen/puppet-homebrew#64]
I noticed that you [manually set the ldflag and cflag](https://github.com/boxen/puppet-homebrew/blob/master/templates/env.sh.erb#L4-L10). This seems to work, however some coworkers have discussed with me that this may cause issues with future compiles that are not homebrew. Is this the best option or is there perhaps another way to do this?

**Comment by mikemcquaid** [comment]
If you can point us to a specific bug then we'll be happy to fix that but otherwise I think we'll leave this as-is for now. Thanks!
