### ISSUE TITLE
brew boxen-install

### ISSUE THREAD

**Issue by lethjakman** [boxen/puppet-homebrew#66]
Should you be forced to always use brew boxen-install application when installing? 

I found [these](https://github.com/boxen/puppet-homebrew/blob/153bcc9f7c1245471e45e3a5f6cfa7f8f91fb348/lib/puppet/provider/package/homebrew.rb#L83-L87) lines and they gave me issues when installing tmux. When I was using brew boxen-install I would have an issue with boxen-install not knowing where a specific version of libevent is. When I use plain brew install tmux however libevent would install properly. I resolved this by passing '--nop' to 'install_options' in order to use plain brew install. Thank you for your time!

**Comment by mikemcquaid** [comment]
Yes, it's needed for e.g. installing Boxen's binary packages.
