### ISSUE TITLE
Request: move Boxen homebrew install to /usr/local

### ISSUE THREAD

**Issue by indirect** [boxen/puppet-homebrew#68]
So right now Boxen has a lot of code (that is getting smaller, thanks @dgoodlad!) to work around the way that homebrew very, very strongly expects to be installed into /usr/local. In addition, keeping homebrew in /opt/boxen/homebrew means that it's not possible to use many of the pre-compiled homebrew bottles.

Boxen's readme already makes it clear that it doesn't work with existing homebrew installs in /usr/local, and rubies are already installed outside /opt/boxen (into /opt/rubies).

Since it seems impractical and/or unlikely that puppet-homebrew will ever have even close to as many compiled binaries as homebrew has bottles, can we just move boxen's homebrew into /usr/local and get bottles for everything for free? As a bonus, it would probably then be possible to stop maintaining the entire `boxen-install` command...

**Comment by toolbear** [comment]
Anticipatory :clap:

I look forward to issues like pkrumins/node-png#45 becoming a thing of the past.

**Comment by indirect** [comment]
Oh yeah! Is this done yet? @dgoodlad, are you done being hungover after RubyConf AU yet? :grinning: (Sorry I didn't manage to say hi! I did see you from across the room and say "hi david" once :stuck_out_tongue:)

**Comment by toolbear** [comment]
@indirect you can change `boxen_root` via `facts.d`, for example: [dd48f30e](https://github.com/boxen/our-boxen/commit/dd48f30eee914549ff99cdd0a9ec5e5fce42dff6).

However, when I did this more things broke for me than when I left it as `/opt/boxen`. I expect this to swing the other way soon enough.

**Comment by mikemcquaid** [comment]
I've been running Boxen's Homebrew in `/usr/local` for a few months now and it's working great.

**Comment by pencil** [comment]
Is there a way to disable the `puppet-homebrew` bottle monkey patches? I switched to `/usr/local` using `boxen_root` but for some reason end up compiling `qt4`.

**Comment by mikemcquaid** [comment]
@pencil The monkey patches won't do that; that'll probably be done by Qt trying to build with an option.

**Comment by mikemcquaid** [comment]
Closing this out as you can now install into `/usr/local` and Homebrew's bottles are used.

**Comment by kylemclaren** [comment]
@mikemcquaid know of an easy way to migrate from `/opt/boxen` to `/usr/local`?

**Comment by mikemcquaid** [comment]
@kylemclaren `sudo rm -rf /opt/boxen/homebrew /opt/rubies` and rerun Boxen.

**Comment by kylemclaren** [comment]
You're a legend, thank you!

**Comment by carrchr** [comment]
wouldn't this command `sudo rm -rf /opt/boxen/homebrew /opt/rubies` nuke all the stuff you've downloaded/installed into home-brew and require re-installing it all? Are you supposed to `mv /opt/boxen/homebrew /usr/local/homebrew` first?

**Comment by MikeMcQuaid** [comment]
> wouldn't this command sudo rm -rf /opt/boxen/homebrew /opt/rubies nuke all the stuff you've downloaded/installed into home-brew and require re-installing it all?

yes

> Are you supposed to mv /opt/boxen/homebrew /usr/local/homebrew first?

no; you cannot move things around like this as paths are hardcoded in binaries.

**Comment by carrchr** [comment]
okay. thank you for the clarification
