### ISSUE TITLE
Fetch of homebrew repo doesn't retry in the face of failures

### ISSUE THREAD

**Issue by mstewart** [boxen/puppet-homebrew#83]
When installing recently I happened to be on a slow network connection during the fetch of the Homebrew/homebrew repo, and the `install homebrew to ${installdir}` task here timed out: https://github.com/boxen/puppet-homebrew/blob/master/manifests/init.pp#L55

When re-running the boxen installed, it didn't retry the fetch, instead skipping past that command as if it had completed successfully (and failing cryptically later).

This behaviour is due to the presence of the `creates => "${installdir}/.git"` attribute in that exec command, which implies that the command doesn't need to be run as long as `.git` exists. But obviously that only means the initial `git init` succeeded, not anything after it.

Since the chain of commands is idempotent and safe to re-run, the "creates" attribute should probably just be removed entirely.

**Comment by salimane** [comment]
:+1:

**Comment by jacobbednarz** [comment]
@mstewart this sounds sane to me - do you mind opening a PR for review?
