### ISSUE TITLE
Not installing to the right directory

### ISSUE THREAD

**Issue by evjan** [boxen/puppet-homebrew#94]
It seems the most recent version(s) of this repo has stopped obeying our command to install homebrew to `/opt/boxen/homebrew`. On a newly set up machine I do `which brew` and I get `/usr/local/bin/brew`, which is not a symlink to any other location. On an older machine set up in the past the same `which brew` yields `/opt/boxen/homebrew/bin/brew`.

Using this to install homebrew in the Puppetfile:
`github "homebrew",    "2.0.2"`

In the past we used puppet-homebrew 1.13.0.

Running OS X 10.11.4

**Comment by akerl** [comment]
This is expected behavior

https://github.com/boxen/puppet-homebrew/commit/d49adf31508a3a218c2da5a4b42ba343e6183200

**Comment by evjan** [comment]
This change was unfortunately very backwards incompatible and has caused a lot of problems for us. Lots of other Boxen modules depend on homebrew being in a specific location, e.g. Python and RabbitMQ. At the very least this change should have been released as a new major version, indicating that it is likely to break things.

**Comment by jacobbednarz** [comment]
Sorry to hear this was a pain point :cry: If you'd like the old directory back, you can set the [install directory](https://github.com/boxen/puppet-homebrew/blob/master/manifests/init.pp#L9) using hiera and have your functionality back to how it was.

Closing but happy to discuss this further if you have any questions.
