### ISSUE TITLE
Support newer versions of homebrew

### ISSUE THREAD

**Issue by jacobbednarz** [boxen/puppet-homebrew#95]
Since homebrew has been split into two repositories now I'd like to update the puppet module to ensure we continue doing things correctly in the future and don't cause weird bugs to our module being out of sync.

@MikeMcQuaid would you be able to share some ideas on how you think this module should progress forward? I understand you don't maintain Boxen any more, however I think you're best placed to understand the changes in Homebrew and Boxen together 😄

**Comment by MikeMcQuaid** [comment]
This repo should actually be fine as-is, I think. It only needs to concern itself with installing `Homebrew/brew` as the core tap will be autotapped when needed (but there would be no harm in automatically running `brew tap homebrew/core` manually anyway). In future I'd mainly just say: stick to use the `brew` command-line interface as the API, do not try to use internal Homebrew classes beyond those already used and just check this module still works on each OS X upgrade.

**Comment by jacobbednarz** [comment]
fixed in boxen/puppet-homebrew#97
